name: DNP
channels:
  - pytorch
  - conda-forge
  - defaults
  - conda-forge/label/gcc7
dependencies:
  - audioread=2.1.6=py37_0
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.2=py37h2e261b9_1
  - cudatoolkit=9.0=h13b8566_0
  - cycler=0.10.0=py_1
  - dbus=1.13.2=h714fa37_1
  - decorator=4.4.0=py_0
  - expat=2.2.5=hf484d3e_1002
  - ffmpeg=4.1.1=h167e202_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.9.1=h8a8886c_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.56.2=had28632_1001
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.5=hd3a4fd2_1002
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=hf484d3e_1000
  - intel-openmp=2019.3=199
  - joblib=0.13.2=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py37h6bb024c_1002
  - lame=3.100=h14c3975_1001
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libflac=1.3.1=hf484d3e_1002
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - libogg=1.3.2=h14c3975_1001
  - libpng=1.6.36=hbc83047_0
  - librosa=0.6.3=py_0
  - libsndfile=1.0.28=hf484d3e_1000
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=2.32.1=h14c3975_1000
  - libvorbis=1.3.5=h14c3975_1001
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.8=h143f9aa_1005
  - llvmlite=0.26.0=py37hdbcaa40_1000
  - matplotlib=3.0.2=py37h8a2030e_1001
  - matplotlib-base=3.0.2=py37h167e16e_1001
  - mkl=2019.3=199
  - mkl_fft=1.0.10=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - ninja=1.9.0=py37hfd86e86_0
  - numba=0.41.0=py37h637b7d7_1000
  - numpy=1.16.2=py37h7e9f1db_0
  - numpy-base=1.16.2=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1b=h14c3975_1
  - pcre=8.43=he6710b0_0
  - pillow=5.4.1=py37h34e0f95_0
  - pip=19.0.3=py37_0
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.19=py37_0
  - pyparsing=2.3.1=py_0
  - pyqt=5.6.0=py37h13b7fb3_1008
  - pysoundfile=0.10.2=pyh14c3975_1000
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py_0
  - pytorch=1.0.1=py3.7_cuda9.0.176_cudnn7.4.2_2
  - qt=5.6.3=h8bf5577_3
  - readline=7.0=h7b6447c_5
  - resampy=0.2.1=py_1
  - scikit-learn=0.20.3=py37hd81dba3_0
  - scipy=1.2.1=py37h7c811a0_0
  - setuptools=40.8.0=py37_0
  - sip=4.18.1=py37hf484d3e_1000
  - six=1.12.0=py37_0
  - sqlite=3.27.2=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.2.2=py_3
  - tornado=6.0.2=py37h516909a_0
  - tqdm=4.31.1=py_0
  - wheel=0.33.1=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0


